### PR TITLE
Hotspots and art

### PR DESCRIPTION
**Pull request by jpbuettgenback**
I finished the hotspots for the church and the convenience store. I couldn't add hotspots to other places because I didn't have updated art assets for the swamp, construction, or Valerie. Aaron says we will have the art in tomorrow, and this pull is to help me understand the pull system.

### CODE REVIEW

**Comment by acurrydish1** [comment]
Just to verify, is this for all future pull requests or this one in particular?

**Comment by pjmanley671** [comment]
In this case it's only this one.

**Comment by acurrydish1** [comment]
kk

**Comment by jpbuettgenback** [comment]
I tried to put it into the unstaged changes, but it gave me an error. Am I just to delete it instead? Still don't really understand github/gitgui

**Pull request closed without merging**
